version: '3.1'

services:
    api_result:
        build: ./api-result-springboot
        ports: 
            - 40000:40000
        networks: 
            - "msa"
        restart: unless-stopped
        environment: 
            - spring.rabbitmq.host=rabbitmq
            - spring.cloud.config.uri=http://config:8012
            - eureka.client.service-url.defaultZone=http://eureka:8010/eureka
            - server.port=40000
            - spring.cloud.config.name=docker
            - spring.zipkin.base-url=zipkin
networks: 
    msa: