version: '3.1'

services:    
    zuul:
        build: ./back-zuul-springboot
        ports: 
            - 8011:8011
        networks: 
            - "msa"
        restart: unless-stopped
        environment:
            - spring.rabbitmq.host=rabbitmq
            - spring.cloud.config.uri=http://config:8012
            - eureka.client.service-url.defaultZone=http://eureka:8010/eureka
            - spring.cloud.config.name=docker

    eureka:
        build: ./back-eureka-springboot
        ports: 
            - 8010:8010
        networks: 
            - "msa"
        restart: unless-stopped
        environment: 
            - eureka.client.service-url.defaultZone=http://localhost:8010/eureka
            - spring.cloud.config.uri=http://config:8012
networks: 
    msa: