version: '3.1'

services:
    rabbitmq:
        image: rabbitmq:management
        ports:
            - 5672:5672
            - 9999:15672
        environment: 
            RABBITMQ_DEFAULT_USER: admin
            RABBITMQ_DEFAULT_PASS: admin
        restart: unless-stopped
        networks: 
            - "msa"
    
    zipkin:
        image: openzipkin/zipkin
        ports:
            - 9411:9411
        networks: 
            - "msa"
        restart: unless-stopped
networks: 
    msa: