version: '3.1'

services:    
    api_user:
        image: ppojin/user
        ports: 
            - 10000:10000
        networks: 
            - "msa"
        # restart: unless-stopped
        environment: 
            - spring.rabbitmq.host=rabbitmq
            - spring.cloud.config.uri=http://config:8012
            - eureka.client.service-url.defaultZone=http://eureka:8010/eureka
            - server.port=20000
            - spring.cloud.config.name=docker
            - spring.zipkin.base-url=zipkin

    api_qabank:
        image: ppojin/qabank
        ports: 
            - 20000:20000
        networks: 
            - "msa"
        # restart: unless-stopped
        environment: 
            - spring.rabbitmq.host=rabbitmq
            - spring.cloud.config.uri=http://config:8012
            - eureka.client.service-url.defaultZone=http://eureka:8010/eureka
            - server.port=20000
            - spring.cloud.config.name=docker
            - spring.zipkin.base-url=zipkin
        depends_on: 
            - api_user

    api_result:
        image: ppojin/result
        ports: 
            - 40000:40000
        networks: 
            - "msa"
        # restart: unless-stopped
        environment: 
            - spring.rabbitmq.host=rabbitmq
            - spring.cloud.config.uri=http://config:8012
            - eureka.client.service-url.defaultZone=http://eureka:8010/eureka
            - server.port=40000
            - spring.cloud.config.name=docker
            - spring.zipkin.base-url=zipkin
        depends_on: 
            - api_qabank
networks: 
    msa: