web:
    image: 'gitlab/gitlab-ee:latest'
    restart: always
    hostname: 'my.localhost'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'https://my.localhost'
    ports:
      - '80:80'
      - '443:443'
      - '22:22'
    volumes:
      - './srv/gitlab/config:/etc/gitlab'
      - './srv/gitlab/logs:/var/log/gitlab'
      - './srv/gitlab/data:/var/opt/gitlab'